[PNUDEV-44] Prevent brute force attacks
PNUdev/shpalta-if pull request #54
Opened 2020-11-17 20:50 UTC by volodymyrvynnyk

Prevent brute force attacks

2020-11-19 22:10 UTC, Igor-Polatajko requested changes
In general, good!
But we need some changes to be applied.

2020-11-19 22:10 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/controller/IndexAdminController.java
> +            TelegramSubscriptionsDashboardInfo telegramDashboardInfo = telegramBotUserService.getSubscriptionsDashboardInfo();
I think it's better to have separate page for this security stuff.

2020-11-19 22:10 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/listener/ApplicationRequestContextListener.java
> +public class ApplicationRequestContextListener extends RequestContextListener {
Do we need this class?

2020-11-19 22:10 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/service/UserServiceImpl.java
> +        HttpServletRequest request = ((ServletRequestAttributes) Objects.requireNonNull(RequestContextHolder.getRequestAttributes()))
I've seen this code couple of times throughout the PR. Move it to util class.

2020-11-19 22:10 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/service/UserServiceImpl.java
> +                           LoginAttemptServiceImpl loginAttemptService, Environment environment,
Formatting

2020-11-19 22:10 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/service/LoginAttemptServiceImpl.java
> +        return FailedLoginAttemptsInfo.builder()
Maybe query db for count?

2020-11-19 22:10 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/service/LoginAttemptServiceImpl.java
> +        attemptsCache.put(ipAddress, attempts);
Do we need this cache??
Just query latest attempt over the past day and check if ip is blocked after.
Application level cache is, sometimes, evil....

2020-11-20 07:54 UTC, volodymyrvynnyk commented on src/main/java/com/pnu/dev/shpaltaif/listener/ApplicationRequestContextListener.java
> +public class ApplicationRequestContextListener extends RequestContextListener {
Yeah, I hope so
It's required to make this method `request.getHeader("X-Forwarded-For")` work.
This Listener makes it possible to get `X-Forwarded-For Header`
I've read about it here https://www.baeldung.com/spring-security-block-brute-force-authentication-attempts#user-details-service

2020-11-22 18:01 UTC, Igor-Polatajko requested changes
Few more comments

2020-11-22 18:01 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/controller/AuthController.java
> +            String errorMessage = "Помилка авторизації";
I'd move error message resolving to private method

2020-11-22 18:01 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/service/LoginAttemptServiceImpl.java
> +        return FailedLoginAttemptsInfo.builder()
any reaction to the comment above?

2020-11-22 18:01 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/service/LoginAttemptServiceImpl.java
> +        List<LoginAttempt> attemptsForLast24Hours = getLoginAttemptsForLast24Hours(ipAddress);
This have to be somehow refactored.

2020-11-22 18:01 UTC, Igor-Polatajko commented on src/main/resources/templates/admin/index.ftl
> +            </td>
Fix markup (have to be `</th>`)

2020-11-22 18:01 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/service/LoginAttemptServiceImpl.java
> +        List<LoginAttempt> attemptsForLast24Hours = getLoginAttemptsForLast24Hours(ipAddress);
And we need to have number of failed attempts since last success for this IP.

2020-11-23 17:41 UTC, Igor-Polatajko approved these changes
Great job!

React to comments before merge

2020-11-23 17:41 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/service/LoginAttemptServiceImpl.java
> +    private final int MAX_ATTEMPTS_NUMBER = 3;
As for me `3` is not enough, `10` suits better.

2020-11-23 17:41 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/controller/AuthController.java
> +        } else if (error.equalsIgnoreCase("blocked")) {
I'd move this value to some enum, because it's not clear where it's coming from, especially when this literal is used in two different classes.

2020-11-23 18:28 UTC, Igor-Polatajko commented on src/main/java/com/pnu/dev/shpaltaif/exception/AuthExceptionMessage.java
> +        throw new ServiceException(String.format("No enums found by message: '%s'", message));
Solution is good, but it doesn't reflect the original logic.

`return "Помилка авторизації";` instead

2020-11-24 09:28 UTC, merged